"""sheet_backend_agnostic

Revision ID: 3a2599d6762c
Revises: 350dd6c00932
Create Date: 2026-02-24 06:57:47.681063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2599d6762c'
down_revision: Union[str, Sequence[str], None] = '350dd6c00932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('library_folder_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('backend_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('backend_file_id', sa.String(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_sheets_drive_file_id'))
        batch_op.create_index(batch_op.f('ix_sheets_backend_file_id'), ['backend_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sheets_library_folder_id'), ['library_folder_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_sheet', ['user_id', 'backend_type', 'backend_file_id'])
        batch_op.create_foreign_key('fk_sheets_library_folder_id', 'library_folders', ['library_folder_id'], ['id'])
        batch_op.drop_column('drive_file_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_file_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_sheets_library_folder_id', type_='foreignkey')
        batch_op.drop_constraint('uq_user_sheet', type_='unique')
        batch_op.drop_index(batch_op.f('ix_sheets_library_folder_id'))
        batch_op.drop_index(batch_op.f('ix_sheets_backend_file_id'))
        batch_op.create_index(batch_op.f('ix_sheets_drive_file_id'), ['drive_file_id'], unique=False)
        batch_op.drop_column('backend_file_id')
        batch_op.drop_column('backend_type')
        batch_op.drop_column('library_folder_id')

    # ### end Alembic commands ###
